fix(types): restore node10 module resolution compatibility
posva/pinia-plugin-debounce pull request #117
Opened 2023-12-14 21:02 UTC by lukashroch

Restores node10 module resolution types (closes #114)

![Capture](https://github.com/posva/pinia-plugin-debounce/assets/223967/9fe3c031-a782-4c43-8bd0-c6aecddbc47a)

2023-12-14 23:02 UTC, posva requested changes

2023-12-14 23:02 UTC, posva commented on package.json
> -        "./dist/*"
let's add `"./*""` to the array instead of removing the values. That should also do for older versions.

2023-12-15 05:38 UTC, posva approved these changes
Thanks a lot, this might seem like little but it really helped me!

2023-12-15 05:39 UTC, merged

2023-12-15 08:54 UTC, lukashroch commented
No problem, glad it helped!

... my initial thought to remove this was that `typesVersions` might be redundant in this case as there was only `*` fallback with no specific ts versions defined, but I'm not that well-versed in these particular type config nuances.